### ISSUE TITLE
CIFAR-10 1000ep pretrained checkpoint

### ISSUE THREAD

**Issue by priyamdey** [MTandHJ/amoc#1]
Hi,

Can you share the model checkpoint for the 1000ep CIFAR-10 pretraining with the batch-size of 256? (Table-2 last row in the paper)

Thanks

**Comment by MTandHJ** [comment]
You can download the pre-trained model now: https://drive.google.com/file/d/1BqwWV7EiSW6Jp_WXKU80kGyFtFuzP9XC/view?usp=sharing
